/* Main.c file generated by New Project wizard
 *
 * Created:   Sat May 11 2024
 * Processor: PIC16F877A
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>

#define _XTAL_FREQ 20000000 // Define the operating frequency

#define MAX_VOLTAGE 5.0 // Maximum voltage range of the sensor (in volts)

void initialize_ADC() {
    // Configure ADCON1 register for analog input channels
    ADCON1bits.PCFG = 0b0000; // Set AN0-AN7 as analog inputs
    // Configure ADCON0 register
    ADCON0bits.ADCS = 0b01; // Fosc/8 as ADC conversion clock
    ADCON0bits.ADON = 1; // Enable ADC module
}

unsigned int read_ADC(unsigned char channel) {
    ADCON0bits.CHS = channel; // Select the specified channel
    __delay_us(10); // Wait for acquisition time (if needed)
    ADCON0bits.GO = 1; // Start ADC conversion
    while (ADCON0bits.GO); // Wait for conversion to complete
    return (ADRESH << 8) | ADRESL; // Return the 10-bit ADC result
}

void __interrupt() ISR() {
    if (INTCONbits.INTF) {
        // Handle RB0 interrupt (manual irrigation)
        if (PORTBbits.RB3 == 0) {
            PORTBbits.RB1 = 1; // Turn on LED connected to RB1
        } else {
            PORTBbits.RB1 = 0; // Turn off LED connected to RB1
        }
        if (PORTBbits.RB4 == 0) {
            PORTBbits.RB4 = 1; // Turn on LED connected to RB4
        } else {
            PORTBbits.RB4 = 0; // Turn off LED connected to RB4
        }

        INTCONbits.INTF = 0; // Clear the RB0 interrupt flag
    }
}

void main() {
    // Initialize ADC module
    initialize_ADC(); 

    // Set RB0, RB1, RB3, and RB4 as inputs/outputs
    TRISBbits.TRISB0 = 1; // Set RB0 as input (interrupt source)
    TRISBbits.TRISB1 = 0; // Set RB1 as output
    TRISBbits.TRISB3 = 1; // Set RB3 as input (manual irrigation switch)
    TRISBbits.TRISB4 = 1; // Set RB4 as input (manual irrigation switch)
    TRISDbits.TRISD0 = 0; // Set RD0 as output
    TRISDbits.TRISD1 = 0; // Set RD1 as output
    TRISDbits.TRISD2 = 0; // Set RD2 as output
    TRISDbits.TRISD3 = 0; // Set RD3 as output
    TRISDbits.TRISD4 = 0; // Set RD4 as output
    TRISDbits.TRISD5 = 0; // Set RD5 as output

    // Configure interrupt on RB0
    OPTION_REGbits.INTEDG = 1; // Interrupt on rising edge
    INTCONbits.INTE = 1;       // Enable RB0/INT external interrupt
    INTCONbits.GIE = 1;        // Enable global interrupts

    // Control LEDs based on sensor values in the main loop
    while(1) {
        // Read analog values of three sensors connected to AN0, AN1, and AN2
        int soil_moisture_1 = read_ADC(0); // Read sensor connected to AN0
        int soil_moisture_2 = read_ADC(1); // Read sensor connected to AN1
        int water_level = read_ADC(2); // Read sensor connected to AN2

        // Determine the values of B1V and B2V based on sensor readings
        int B1V, B2V;
        if (soil_moisture_1 > (40 * 1024 / MAX_VOLTAGE) &&
            soil_moisture_2 > (60 * 1024 / MAX_VOLTAGE) &&
            water_level > (20 * 1024 / MAX_VOLTAGE)) {
            B2V = 1;
            B1V = 1;
        } else if (soil_moisture_1 < (40 * 1024 / MAX_VOLTAGE) &&
                   soil_moisture_2 < (40 * 1024 / MAX_VOLTAGE)) {
            B2V = 0;
            B1V = 0;
        } else if (soil_moisture_1 <= (40 * 1024 / MAX_VOLTAGE) &&
                   water_level > (20 * 1024 / MAX_VOLTAGE)) {
            B1V = 1;
            B2V = 0;
        } else if (soil_moisture_2 <= (60 * 1024 / MAX_VOLTAGE) &&
                   water_level > (20 * 1024 / MAX_VOLTAGE)) {
            B1V = 0;
            B2V = 1;
        } else {
            B2V = 0;
            B1V = 0;
        }
        // Control LEDs based on B1V and B2V
        PORTBbits.RB0 = B1V; // Turn on RB0 if B1V is 1
        PORTBbits.RB1 = B2V; // Turn on RB1 if B2V is 1

        // Add delay to slow down sensor readings
        unsigned int temp = soil_moisture_1 * 100 / 255;

        // Initialize Tens and Ones
        int Tens = temp / 10;
        int Ones = temp % 10;

        // Perform division by 10 to separate Tens and Ones
        PORTD = Ones;
        PORTDbits.RD5 = 0; // Enable Ones display (active low)
        __delay_ms(2);     // Small delay for display
        PORTDbits.RD5 = 1; // Disable Ones display
        PORTD = 0;         // Clear PORTD to avoid ghosting

        // Display Tens
        PORTD = Tens;
        PORTDbits.RD4 = 0; // Enable Tens display (active low)
        __delay_ms(2);     // Small delay for display
        PORTDbits.RD4 = 1; // Disable Tens display
        PORTD = 0;         // Clear PORTD to avoid ghosting
    }
}
